[package]
name = "shmr"
version = "0.1.0"
edition = "2021"

[dependencies]
reed-solomon-erasure = { version = "6.0", features = [ "simd-accel" ] }
tokio = { version="1.36", features=["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9.33" }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"

fuser = "0.14"

sled = "0.34"
rkyv = { version = "0.7", features = ["validation"]}
libc = "0.2.153"
clap = { version = "4.5.3", features = ["derive"]}
rand = "0.9.0-alpha.1"

seahash = "4.1"
walkdir = "2.5.0"