mount_dir: ./mnt
metadata_dir: ./metadata
metadata_format: yaml

write_pool: pool0

# Disk Pools
# Each pool can be considered a tier in the filesystem.
# It is recommended that the write_pool be a standard RAID backed Filesystem, as shmr makes no attempt to ensure
# redundancy in this pool by default.
pools:
  pool0:
    p0:
      path: ./pool0
  pool1:
    d0:
      path: ./pool1/0
    d1:
      path: ./pool1/1

  pool2:
    sda:
      path: /mnt/sda
    sdb:
      path: /mnt/sdb
    sdc:
      path: /mnt/sdc
    sdd:
      path: /mnt/sdd
    sde:
      path: /mnt/sde
    sdf:
      path: /mnt/sdf
    sdg:
      path: /mnt/sdg
    sdh:
      path: /mnt/sdh

#  ssd0:
#    CT480BX500SSD1_2029E407F807: /mnt/by-id/ata-CT480BX500SSD1_2029E407F807
#    CT480BX500SSD1_2029E407F808: /mnt/by-id/ata-CT480BX500SSD1_2029E407F806
#    CT480BX500SSD1_2029E407F809: /mnt/by-id/ata-CT480BX500SSD1_2029E407F808
#    CT480BX500SSD1_2029E407F810: /mnt/by-id/ata-CT480BX500SSD1_2029E407F809
#    CT480BX500SSD1_2029E407F811: /mnt/by-id/ata-CT480BX500SSD1_2029E407F805
#
#  hdd:

block_size: 32MB